name: iOS Build (No Mac Needed)

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ✅ Install required dependencies early
      - name: Install Required Build Tools
        run: |
          brew install autoconf automake libtool

      - name: Install Kivy and dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install Cython kivy kivy-ios

      - name: Build Kivy iOS dependencies
        run: |
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios
          python3 toolchain.py build python3 kivy

      # ✅ Attempt to create the iOS project
      - name: Create iOS project
        run: |
          cd kivy-ios
          python3 toolchain.py create visitor_app org.example.visitorapp
          echo "Checking directory structure after create..."
          ls -la  # Debugging: See if visitor_app-ios exists

      # ✅ Check if the correct directory exists BEFORE the build starts
      - name: Verify iOS project directory
        run: |
          if [ -d "kivy-ios/visitor_app-ios" ]; then
            echo "✅ visitor_app-ios exists, renaming to app-ios..."
            mv kivy-ios/visitor_app-ios kivy-ios/app-ios
          else
            echo "❌ ERROR: visitor_app-ios is missing! Build cannot continue."
            ls -la kivy-ios  # Show what's inside kivy-ios
            exit 1
          fi

      # ✅ Now we can proceed safely
      - name: Compile App for iOS
        run: |
          cd kivy-ios/app-ios
          python3 toolchain.py build myapp

      - name: Package iOS app
        run: |
          cd kivy-ios/app-ios
          mkdir -p output
          mv build/myapp.app output/

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: visitor-app-ios
          path: kivy-ios/app-ios/output
