name: iOS Build (No Mac Needed)

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # ✅ Install required dependencies
      - name: Install Required Build Tools
        run: |
          brew install autoconf automake libtool

      # ✅ Install required Python packages
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install Cython kivy kivy-ios sh

      - name: Clone Kivy iOS Repository
        run: |
          git clone https://github.com/kivy/kivy-ios.git

      # ✅ Clean previous builds (ensures a fresh build)
      - name: Clean Kivy iOS Build Directory
        run: |
          cd kivy-ios
          rm -rf dist build
          mkdir -p dist build
          ls -la dist  # Debug: Check if clean

      # ✅ Build Python3 for iOS with debug logs
      - name: Build Python3 for iOS
        run: |
          cd kivy-ios
          python3 toolchain.py build python3 --debug
          echo "Listing contents of kivy-ios/dist after Python3 build:"
          ls -la dist  # Debugging: Check if python3 is present

      # ✅ Verify Python3 Recipe is Compiled
      - name: Verify Python3 Recipe is Compiled
        run: |
          if [ ! -d "kivy-ios/dist/python3" ]; then
            echo "❌ ERROR: Python3 was not compiled successfully!"
            ls -la kivy-ios/dist  # Show contents of dist folder
            echo "⚠️ Possible Fix: Check for missing dependencies in the build logs above."
            exit 1
          else
            echo "✅ Python3 recipe is successfully compiled."
          fi

      - name: Build Kivy iOS dependencies
        run: |
          cd kivy-ios
          python3 toolchain.py build kivy --debug

      - name: Create iOS project
        run: |
          cd kivy-ios
          python3 toolchain.py create visitor_app org.example.visitorapp
          echo "Checking directory structure after create..."
          ls -la  # Debugging: See if visitor_app-ios exists

      - name: Verify iOS project directory
        run: |
          if [ -d "kivy-ios/visitor_app-ios" ]; then
            echo "✅ visitor_app-ios exists, renaming to app-ios..."
            mv kivy-ios/visitor_app-ios kivy-ios/app-ios
          else
            echo "❌ ERROR: visitor_app-ios is missing! Build cannot continue."
            ls -la kivy-ios  # Show what's inside kivy-ios
            exit 1
          fi

      - name: Compile App for iOS
        run: |
          cd kivy-ios/app-ios
          python3 toolchain.py build myapp

      - name: Package iOS app
        run: |
          cd kivy-ios/app-ios
          mkdir -p output
          mv build/myapp.app output/

      - name: Upload iOS build
        uses: actions/upload-artifact@v4
        with:
          name: visitor-app-ios
          path: kivy-ios/app-ios/output
