name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest  # Ensure macOS runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew install autoconf automake libtool
          python3 -m pip install --upgrade pip setuptools wheel cython
          python3 -m pip install kivy-ios

      - name: Clone Kivy iOS
        run: |
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios

      - name: Verify Dependencies Installed
        run: |
          brew list | grep -E "autoconf|automake|libtool"
          python3 -m pip list | grep -E "cython|kivy-ios"

      - name: Force Build Python3 Before Anything Else
        run: |
          cd kivy-ios
          python3 toolchain.py build python3
          
      - name: Check if Python3 Compiled
        run: |
          if [ ! -d "kivy-ios/dist/python3" ]; then
            echo "❌ ERROR: Python3 was not compiled successfully!"
            ls -la kivy-ios/dist  # Show contents for debugging
            exit 1
          else
            echo "✅ Python3 compiled successfully."
          fi

      - name: Build Kivy iOS Dependencies
        run: |
          cd kivy-ios
          python3 toolchain.py build kivy

      - name: Create iOS Project
        run: |
          cd kivy-ios
          python3 toolchain.py create visitor_app

      - name: Compile App for iOS
        run: |
          if [ ! -d "kivy-ios/app-ios" ]; then
            echo "❌ ERROR: app-ios is missing!"
            ls -la kivy-ios  # Show contents for debugging
            exit 1
          fi
          cd kivy-ios/app-ios
          xcodebuild -project visitor_app.xcodeproj -scheme visitor_app -sdk iphonesimulator

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: visitor_app_ios
          path: kivy-ios/app-ios/build
          retention-days: 7
