name: Build Kivy iOS App

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip3 install Cython kivy kivy-ios

      - name: Build Kivy iOS dependencies
        run: |
          git clone https://github.com/kivy/kivy-ios.git
          cd kivy-ios
          python3 toolchain.py build python3 kivy

      - name: Create Xcode project
        run: |
          cd kivy-ios
          python3 toolchain.py create myapp org.example.myapp
          cd app-ios
          mv ../../main.py .

      - name: Build Xcode project
        run: |
          cd kivy-ios/app-ios
          xcodebuild -project myapp.xcodeproj -scheme myapp -destination 'generic/platform=iOS' build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: visitor-app-ios
          path: kivy-ios/app-ios/build
