name: Build Kivy iOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        run: |
          brew install python3
          python3 -m venv kivy_venv
          source kivy_venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install kivy kivy-ios

          # Locate kivy-ios manually and set it to PATH
          export KIVY_IOS_PATH=$(find $HOME/kivy_venv -name "kivy-ios" -type f | head -n 1)
          echo "KIVY_IOS_PATH=$KIVY_IOS_PATH" >> $GITHUB_ENV
          echo "export PATH=$(dirname $KIVY_IOS_PATH):$PATH" >> $GITHUB_ENV
          
          # Debugging: Print if kivy-ios was found
          if [ -z "$KIVY_IOS_PATH" ]; then
            echo "ERROR: kivy-ios not found after installation!"
            exit 1
          else
            echo "Kivy-iOS is installed at: $KIVY_IOS_PATH"
          fi

      - name: Build iOS App
        run: |
          source kivy_venv/bin/activate
          kivy-ios create myapp
          cd myapp
          TOOLCHAIN=toolchain.py
          python3 $TOOLCHAIN build python3 kivy
          python3 $TOOLCHAIN build myapp

      - name: Export IPA File
        run: |
          source kivy_venv/bin/activate
          cd myapp
          python3 $TOOLCHAIN package myapp

      - name: Upload IPA File
        uses: actions/upload-artifact@v4
        with:
          name: kivy-ios-app
          path: myapp/bin/*.ipa
