name: Build Kivy iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏗 Install System Dependencies (Skip if already done)
        id: check_installation
        run: |
          brew update
          brew install python3 autoconf automake libtool pkg-config
          echo "::set-output name=installed::true"

      - name: 🏗 Install Python and Dependencies (Skip if already done)
        if: steps.check_installation.outputs.installed != 'true'
        run: |
          # Create and activate virtual environment
          python3 -m venv $HOME/kivy_venv
          source $HOME/kivy_venv/bin/activate

          # Upgrade pip and install required dependencies
          python3 -m pip install --upgrade pip
          python3 -m pip install kivy

          # Install kivy-ios from official source
          python3 -m pip install kivy-ios --no-cache-dir

          # Locate and export Kivy-iOS path
          export KIVY_IOS_PATH=$(python3 -c "import kivy_ios, os; print(os.path.dirname(kivy_ios.__file__))")

          # Debug: Ensure kivy-ios is correctly installed
          echo "Kivy-iOS path: $KIVY_IOS_PATH"
          ls -la $KIVY_IOS_PATH

          # Debug: Ensure toolchain.py exists
          TOOLCHAIN_PATH="$KIVY_IOS_PATH/toolchain.py"
          echo "Toolchain path: $TOOLCHAIN_PATH"
          ls -la $KIVY_IOS_PATH

          if [ ! -d "$KIVY_IOS_PATH" ]; then
            echo "❌ ERROR: kivy-ios installation path is invalid: $KIVY_IOS_PATH"
            exit 1
          fi

          if [ ! -f "$TOOLCHAIN_PATH" ]; then
            echo "❌ ERROR: toolchain.py not found at $TOOLCHAIN_PATH"
            exit 1
          fi

          # Add kivy-ios to PATH and persist across steps
          echo "export PATH=$KIVY_IOS_PATH:\$PATH" >> $HOME/.bashrc
          echo "KIVY_IOS_PATH=$KIVY_IOS_PATH" >> $GITHUB_ENV

      - name: 🔨 Build iOS App (Resume if previously failed)
        if: success()  # Only run if the previous steps were successful
        run: |
          source $HOME/kivy_venv/bin/activate

          # Ensure kivy-ios is installed
          python3 -m pip show kivy-ios || { echo "❌ kivy-ios is missing!"; exit 1; }

          # Ensure toolchain.py is available
          TOOLCHAIN_PATH="$KIVY_IOS_PATH/toolchain.py"
          echo "Toolchain path: $TOOLCHAIN_PATH"
          ls -la $KIVY_IOS_PATH  # List contents to check for toolchain.py

          if [ ! -f "$TOOLCHAIN_PATH" ]; then
            echo "❌ ERROR: toolchain.py not found at $TOOLCHAIN_PATH"
            exit 1
          else
            echo "✅ Found toolchain.py at: $TOOLCHAIN_PATH"
          fi

          # ✅ Ensure app directory exists and create inside the working directory
          mkdir -p $HOME/myapp
          cd $HOME/myapp

          # 🔧 Ensure python3 recipe is compiled first
          python3 $TOOLCHAIN_PATH build python3

          # Build Kivy and app dependencies
          python3 $TOOLCHAIN_PATH build kivy

          # 🔥 Manually create a recipe for your app before building
          python3 $TOOLCHAIN_PATH create myapp

          # Build the app
          python3 $TOOLCHAIN_PATH build myapp

      - name: 📦 Package IPA File
        if: success()  # Only run if the build step succeeded
        run: |
          source $HOME/kivy_venv/bin/activate
          cd $HOME/myapp
          python3 $KIVY_IOS_PATH/toolchain.py package myapp

      - name: 📤 Upload IPA File
        if: success()  # Only run if the previous step succeeded
        uses: actions/upload-artifact@v4
        with:
          name: kivy-ios-app
          path: $HOME/myapp/bin/*.ipa
