name: Build Kivy iOS App

on: 
  push:
    branches:
      - main
    # Trigger only if the YAML or code changes
    paths:
      - '**.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          brew install python3 autoconf automake libtool
          python3 -m venv $HOME/kivy_venv
          source $HOME/kivy_venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install kivy kivy-ios sh  # Added sh installation

          # Find kivy-ios path dynamically
          export KIVY_IOS_PATH=$(python3 -c "import kivy_ios, os; print(os.path.dirname(kivy_ios.__file__))")

          # Debugging: Ensure kivy-ios is found
          if [ ! -d "$KIVY_IOS_PATH" ]; then
            echo "❌ ERROR: kivy-ios installation path is invalid: $KIVY_IOS_PATH"
            exit 1
          else
            echo "✅ Kivy-iOS is installed at: $KIVY_IOS_PATH"
          fi

          # Persist environment variables
          echo "export KIVY_IOS_PATH=$KIVY_IOS_PATH" >> $HOME/.bashrc
          echo "KIVY_IOS_PATH=$KIVY_IOS_PATH" >> $GITHUB_ENV

      - name: Build iOS App
        run: |
          source $HOME/kivy_venv/bin/activate

          # Check if the Python build exists, if it does, skip the build
          if [ -f "myapp/.python3-built" ]; then
            echo "✅ Python recipe already built. Skipping Python build."
          else
            echo "❌ Python build not found. Building Python recipe."
            python3 $KIVY_IOS_PATH/toolchain.py build python3 --dir myapp
            touch myapp/.python3-built # Mark Python build as completed
          fi

          # Check if Kivy build exists, if it does, skip the build
          if [ -f "myapp/.kivy-built" ]; then
            echo "✅ Kivy recipe already built. Skipping Kivy build."
          else
            echo "❌ Kivy build not found. Building Kivy recipe."
            python3 $KIVY_IOS_PATH/toolchain.py build kivy --dir myapp
            touch myapp/.kivy-built # Mark Kivy build as completed
          fi

          # Build iOS App
          python3 $KIVY_IOS_PATH/toolchain.py build myapp --dir myapp

      - name: Export IPA File
        run: |
          source $HOME/kivy_venv/bin/activate
          cd myapp
          python3 $KIVY_IOS_PATH/toolchain.py package myapp

      - name: Upload IPA File
        uses: actions/upload-artifact@v4
        with:
          name: kivy-ios-app
          path: myapp/bin/*.ipa
