name: Build Kivy iOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and Dependencies
        run: |
          brew install python3

          # Ensure virtual environment exists
          python3 -m venv $HOME/kivy_venv
          source $HOME/kivy_venv/bin/activate

          python3 -m pip install --upgrade pip
          python3 -m pip install kivy kivy-ios

          # Manually find and set the correct kivy-ios path
          export KIVY_IOS_PATH=$(python3 -c "import kivy_ios, os; print(os.path.dirname(kivy_ios.__file__))")

          # Debugging: Ensure kivy-ios is found
          if [ ! -d "$KIVY_IOS_PATH" ]; then
            echo "❌ ERROR: kivy-ios installation path is invalid: $KIVY_IOS_PATH"
            exit 1
          else
            echo "✅ Kivy-iOS is installed at: $KIVY_IOS_PATH"
          fi

          # Add kivy-ios to PATH
          echo "export PATH=$KIVY_IOS_PATH:$PATH" >> $HOME/.bashrc
          echo "KIVY_IOS_PATH=$KIVY_IOS_PATH" >> $GITHUB_ENV

      - name: Build iOS App
        run: |
          source $HOME/kivy_venv/bin/activate
      
          # Create the app directory properly
          python3 -m kivy_ios.toolchain create myapp
          cd myapp
      
          # Set the correct TOOLCHAIN path
          TOOLCHAIN=$KIVY_IOS_PATH/toolchain.py
      
          # Fix: Ensure toolchain.py is correctly used with required arguments
          python3 $TOOLCHAIN build python3 --dir .
          python3 $TOOLCHAIN build kivy --dir .
          python3 $TOOLCHAIN build myapp --dir .

      - name: Export IPA File
        run: |
          source $HOME/kivy_venv/bin/activate
          cd myapp
          python3 $TOOLCHAIN package myapp

      - name: Upload IPA File
        uses: actions/upload-artifact@v4
        with:
          name: kivy-ios-app
          path: myapp/bin/*.ipa
