name: Build Kivy iOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          brew install python3 autoconf automake libtool
          python3 -m venv $HOME/kivy_venv
          source $HOME/kivy_venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install kivy kivy-ios

          # Find kivy-ios path dynamically
          export KIVY_IOS_PATH=$(python3 -c "import kivy_ios, os; print(os.path.dirname(kivy_ios.__file__))")

          # Debugging: Ensure kivy-ios is found
          if [ ! -d "$KIVY_IOS_PATH" ]; then
            echo "❌ ERROR: kivy-ios installation path is invalid: $KIVY_IOS_PATH"
            exit 1
          else
            echo "✅ Kivy-iOS is installed at: $KIVY_IOS_PATH"
          fi

          # Persist environment variables
          echo "export KIVY_IOS_PATH=$KIVY_IOS_PATH" >> $HOME/.bashrc
          echo "KIVY_IOS_PATH=$KIVY_IOS_PATH" >> $GITHUB_ENV

      - name: Build iOS App
        run: |
          source $HOME/kivy_venv/bin/activate

          # Install missing dependencies
          brew install autoconf automake libtool

          # Verify Kivy-iOS installation path
          TOOLCHAIN_PATH="$KIVY_IOS_PATH/toolchain.py"
          if [ ! -f "$TOOLCHAIN_PATH" ]; then
            echo "❌ Error: toolchain.py not found at $TOOLCHAIN_PATH"
            exit 1
          fi

          # Create the app project if not already created
          if [ ! -d "myapp" ]; then
            python3 $TOOLCHAIN_PATH create myapp
          fi
          cd myapp

          # **Fix: Explicitly build Python first before anything else**
          python3 $TOOLCHAIN_PATH build python3

          # Check if Python3 was built successfully
          if [ ! -d "$KIVY_IOS_PATH/recipes/python3" ]; then
            echo "❌ Error: Python3 recipe was not compiled!"
            exit 1
          fi

          # **Fix: Ensure Kivy is built before attempting app build**
          python3 $TOOLCHAIN_PATH build kivy

          # **Fix: Ensure myapp exists before building**
          if [ ! -d "$KIVY_IOS_PATH/recipes/myapp" ]; then
            echo "❌ Error: myapp recipe does not exist!"
            exit 1
          fi

          # Now build the actual app
          python3 $TOOLCHAIN_PATH build myapp

      - name: Export IPA File
        run: |
          source $HOME/kivy_venv/bin/activate
          cd myapp
          python3 $TOOLCHAIN_PATH package myapp

      - name: Upload IPA File
        uses: actions/upload-artifact@v4
        with:
          name: kivy-ios-app
          path: myapp/bin/*.ipa
