name: Build Kivy iOS App

on: [push]  # Runs the workflow when you push changes to GitHub

jobs:
  build:
    runs-on: macos-latest  # Uses a macOS machine for iOS builds
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Latest version of checkout action

      - name: Set up Python Environment
        run: |
          brew install python3
          python3 -m venv kivy_venv  # Create a virtual environment
          echo "VIRTUAL_ENV=$PWD/kivy_venv" >> $GITHUB_ENV  # Set venv path
          echo "$PWD/kivy_venv/bin" >> $GITHUB_PATH  # Add venv to PATH
          source kivy_venv/bin/activate  # Activate venv
          python3 -m pip install --upgrade pip
          python3 -m pip install kivy kivy-ios  # Install kivy-ios
          echo "KIVY_IOS_PATH=$(which kivy-ios)" >> $GITHUB_ENV  # Save kivy-ios path

      - name: Build iOS App
        run: |
          source kivy_venv/bin/activate
          $KIVY_IOS_PATH create myapp  # Use full path to kivy-ios
          cd myapp
          TOOLCHAIN=toolchain.py
          python3 $TOOLCHAIN build python3 kivy
          python3 $TOOLCHAIN build myapp

      - name: Export IPA File
        run: |
          source kivy_venv/bin/activate
          cd myapp
          python3 $TOOLCHAIN package myapp

      - name: Upload IPA File
        uses: actions/upload-artifact@v4  # Latest version
        with:
          name: kivy-ios-app
          path: myapp/bin/*.ipa
